import type { LanguageCode } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import { DashboardHeader } from "~/components/DashboardHeader";
import { EmptyPlaceholder } from "~/components/EmptyPlaceholder";
import RestaurantCreateForm from "~/components/Forms/RestaurantCreateForm";
import { Icons } from "~/components/Icons";
import RestaurantItem from "~/components/RestaurantItem";
import Button from "~/components/ui/Button";
import useModal from "~/hooks/useModal";
import DashboardLayout from "~/layouts/Dashboard.layout";
import { api } from "~/utils/api";
import { formatTranslationToOneLanguage } from "~/utils/formatTranslationToOneLanguage";

const RestaurantList = () => {
  const { isModalOpen, toggleModal } = useModal();

  const router = useRouter();

  const { data: restaurants, status } =
    api.restaurant.getAllRestaurants.useQuery(undefined, {
      select: (restaurants) =>
        formatTranslationToOneLanguage(
          restaurants,
          router.locale as LanguageCode
        ),
    });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        <DashboardHeader
          heading="Restaurants"
          text="Create and manage restaurants"
        >
          <Button onClick={toggleModal}>
            <Icons.add className="mr-2 h-4 w-4" />
            New Restaurant
          </Button>
        </DashboardHeader>
        <div className="grid gap-10">
          {status === "loading" && <div>loading</div>}
          {status === "success" && (
            <>
              {restaurants?.length ? (
                <div className="divide-y divide-border rounded-md border">
                  {restaurants.map((restaurant) => (
                    <RestaurantItem
                      key={restaurant.id}
                      restaurant={restaurant}
                    />
                  ))}
                </div>
              ) : (
                <EmptyPlaceholder>
                  <EmptyPlaceholder.Icon name="store" />
                  <EmptyPlaceholder.Title>
                    No restaurants created
                  </EmptyPlaceholder.Title>
                  <EmptyPlaceholder.Description>
                    You don&apos;t have any restaurants yet. Start creating
                    content.
                  </EmptyPlaceholder.Description>
                  <Button variant="outline" onClick={toggleModal}>
                    <Icons.add className="mr-2 h-4 w-4" />
                    New Restaurant
                  </Button>
                </EmptyPlaceholder>
              )}
            </>
          )}
        </div>
      </DashboardLayout>

      {isModalOpen && (
        <RestaurantCreateForm
          isModalOpen={isModalOpen}
          toggleModal={toggleModal}
        />
      )}
    </>
  );
};

export default RestaurantList;
