import Head from "next/head";
import { useTranslations } from "next-intl";
import React from "react";

import { DashboardHeader } from "~/components/DashboardHeader";
import DashboardLayout from "~/layouts/Dashboard.layout";
import { getServerSidePropsWithLanguage } from "~/helpers/getServerSidePropsWithLanguage";

const Settings = () => {
  const t = useTranslations("Dashboard.page.settings");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        <DashboardHeader heading={t("title")} text={t("description")} />
        <div className="grid gap-10">
          {/* <UserNameForm user={{ id: user.id, name: user.name || "" }} /> */}
        </div>
      </DashboardLayout>
    </>
  );
};

export const getServerSideProps = getServerSidePropsWithLanguage;

export default Settings;
