import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import Features from "~/components/LandingSections/Features";
import Hero from "~/components/LandingSections/Hero";
import MarketingLayout from "~/layouts/Marketing.layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MarketingLayout>
        <Hero />
        <Features />
      </MarketingLayout>
    </>
  );
};

export default Home;
