import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";

import { Icons } from "~/components/Icons";
import Menu from "~/components/Menu/Menu";
import { ModeToggle } from "~/components/ModeToggle";
import RestaurantLayout from "~/layouts/Restaurant.layout";

const categories = ["hamburgers", "juices"];

const products = [
  {
    category: "hamburgers",
    name: "bigmac",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/8b28d671de8911edb6fcf91e983811c9_11edcc8aa1c1286ba6ec99b1ded312f0_900_900_520x520.jpeg",
  },
  {
    category: "hamburgers",
    name: "royal",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/8b28d671de8911edb6fcf91e983811c9_11edcc8aa1c1286ba6ec99b1ded312f0_900_900_520x520.jpeg",
  },
  {
    category: "hamburgers",
    name: "bigtasy",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/8b28d671de8911edb6fcf91e983811c9_11edcc8aa1c1286ba6ec99b1ded312f0_900_900_520x520.jpeg",
  },
  {
    category: "hamburgers",
    name: "bigtasy",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/8b28d671de8911edb6fcf91e983811c9_11edcc8aa1c1286ba6ec99b1ded312f0_900_900_520x520.jpeg",
  },
  {
    category: "juices",
    name: "orange",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/2868f5ebde9f11edb7502b8a8bb89127_11edcc912fa501fdbe8a61e83d29bf99_0_0_520x520.jpeg",
  },
  {
    category: "juices",
    name: "apple",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/2868f5ebde9f11edb7502b8a8bb89127_11edcc912fa501fdbe8a61e83d29bf99_0_0_520x520.jpeg",
  },
  {
    category: "juices",
    name: "cherry",
    description: "test description",
    url: "https://menusa.dodostatic.net/images/2868f5ebde9f11edb7502b8a8bb89127_11edcc912fa501fdbe8a61e83d29bf99_0_0_520x520.jpeg",
  },
];

const Restaurant: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RestaurantLayout>
        {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"> */}
        <div className="container flex flex-col items-center justify-center gap-8   md:max-w-screen-lg">
          {/* name and switcher */}
          <div className="sticky top-0 z-40 flex w-full justify-between bg-background py-3">
            <h1 className="text-3xl font-bold">Shawerma 24</h1>
            <ModeToggle />
          </div>
          {/* general info */}
          <div className="grid grid-cols-1 gap-4  md:grid-cols-2">
            <div className=" relative h-80">
              <Image
                src="https://menusa.dodostatic.net/images/7740007bde8911ed8368719f3939c0be_11edcc86977e0ce38c1e0a0a21479180_1200_900.jpg"
                alt="Photo by DoDo"
                fill
                className="rounded-3xl object-cover"
              />
            </div>
            <div className="flex flex-col justify-center gap-5 rounded-3xl border p-5 ">
              <div className="flex gap-3">
                <Icons.clock2 className="shrink-0" />{" "}
                <span className="font-semibold"> from 9:00 to 21:00</span>
              </div>
              <div className="flex gap-3">
                <Icons.mapPin className="shrink-0" />
                <span className="font-semibold">Moscow, Arbat St. 47</span>
              </div>
              <div className="flex gap-3">
                <Icons.store className="shrink-0" />
                <span className="font-semibold">
                  Hearty doners in a pleasant atmosphere. You can quickly order
                  on the way and without a queue through the application. We
                  look forward to visiting!
                </span>
              </div>
            </div>
          </div>

          <Menu />
        </div>
      </RestaurantLayout>
    </>
  );
};

export default Restaurant;
