import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import { DashboardHeader } from "~/components/DashboardHeader";
import DashboardRestaurantHeaderContent from "~/components/DashboardRestaurantHeaderContent";
import RestaurantUpdateForm from "~/components/Forms/RestaurantUpdateForm";
import useGetRestaurant from "~/hooks/useGetRestaurant";
import DashboardLayout from "~/layouts/Dashboard.layout";

const RestaurantDetails = () => {
  const router = useRouter();
  const { data: restaurant, status } = useGetRestaurant(
    router.query.restaurantId as string
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        {status === "loading" && <div>loading</div>}
        {status === "success" && (
          <>
            <DashboardHeader
              heading={restaurant.restaurantI18N.name}
              text="Manage restaurant"
            >
              <DashboardRestaurantHeaderContent restaurant={restaurant} />
            </DashboardHeader>
            <div className="grid gap-10">
              {/*  Update main details */}
              <div>
                <RestaurantUpdateForm restaurant={restaurant} />
              </div>
            </div>
          </>
        )}
      </DashboardLayout>
    </>
  );
};

export default RestaurantDetails;
