import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import CategoriesBlock from "~/components/CategoriesBlock";
import { DashboardHeader } from "~/components/DashboardHeader";
import DashboardRestaurantHeaderContent from "~/components/DashboardRestaurantHeaderContent";
import useGetRestaurant from "~/hooks/useGetRestaurant";
import DashboardLayout from "~/layouts/Dashboard.layout";

const RestaurantCategoriesAndProducts = () => {
  const router = useRouter();

  const { data: restaurant, status } = useGetRestaurant(
    router.query.restaurantId as string
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        {status === "loading" && <div>loading</div>}
        {status === "success" && (
          <>
            <DashboardHeader
              heading={`${restaurant.restaurantI18N.name}`}
              text="Manage restaurant"
            >
              <DashboardRestaurantHeaderContent restaurant={restaurant} />
            </DashboardHeader>
            <div className="grid gap-10">
              <>
                {/* // Category block */}
                <div className="min-w-0">
                  <CategoriesBlock restaurant={restaurant} />
                </div>
              </>
            </div>
          </>
        )}
      </DashboardLayout>
    </>
  );
};

export default RestaurantCategoriesAndProducts;
