import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import CategoriesBlock from "~/components/CategoriesBlock";
import { DashboardHeader } from "~/components/DashboardHeader";
import RestaurantLanguageSelector from "~/components/RestaurantLanguageSelector";
import useGetRestaurant from "~/hooks/useGetRestaurant";
import RestaurantDashboardLayout from "~/layouts/RestaurantDashboard.layout";

const RestaurantCategoriesAndProducts = () => {
  const router = useRouter();
  const { data: restaurant, status } = useGetRestaurant(
    router.query.restaurantId as string
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RestaurantDashboardLayout>
        <DashboardHeader
          heading={`${(restaurant?.restaurantI18N.name as string) || ""}`}
          text="Manage restaurant"
        >
          {!!restaurant && (
            <RestaurantLanguageSelector restaurant={restaurant} />
          )}
        </DashboardHeader>
        <div className="grid gap-10">
          {status === "loading" && <div>loading</div>}
          {status === "success" && (
            <>
              {/* // Category block */}
              <div>
                <CategoriesBlock restaurant={restaurant} />
              </div>
            </>
          )}
        </div>
      </RestaurantDashboardLayout>
    </>
  );
};

export default RestaurantCategoriesAndProducts;
