import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import { DashboardHeader } from "~/components/DashboardHeader";
import LanguagesBlock from "~/components/LanguagesBlock";
import useGetRestaurant from "~/hooks/useGetRestaurant";
import DashboardLayout from "~/layouts/Dashboard.layout";

const RestaurantSettings = () => {
  const router = useRouter();

  const { data: restaurant, status } = useGetRestaurant(
    router.query.restaurantId as string
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        <DashboardHeader
          heading="Settings"
          text="Manage restaurant settings."
        />
        <div className="grid gap-10">
          {status === "loading" && <div>loading</div>}
          {status === "success" && (
            <>
              {/* // Language block */}
              <div>
                <LanguagesBlock restaurant={restaurant} />
              </div>
            </>
          )}
        </div>
      </DashboardLayout>
    </>
  );
};

export default RestaurantSettings;
