import type { LanguageCode } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import { DashboardHeader } from "~/components/DashboardHeader";
import DashboardLayout from "~/layouts/Dashboard.layout";
import { api } from "~/utils/api";

const RestaurantList = () => {
  const router = useRouter();

  const { data: restaurant, status } = api.restaurant.getRestaurant.useQuery(
    {
      restaurantId: router.query.restaurantId as string,
      languageCode: router.locale as LanguageCode,
    },
    { enabled: Boolean(router.locale) }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* TODO: REMOVE ON ANOTHER LAYOUT */}
      <DashboardLayout>
        <DashboardHeader heading="Restaurant" text="Manage restaurant" />
        <div className="grid gap-10">
          {status === "loading" && <div> loading</div>}
          {status === "success" && <div> SINGLE RESTAURANT PAGE</div>}
        </div>
      </DashboardLayout>
    </>
  );
};

export default RestaurantList;
